[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#545652"
blue = "#729ECF"
cyan = "#34E2E2"
green = "#89E234"
magenta = "#AC7EA8"
red = "#EF2828"
white = "#EDEDEB"
yellow = "#FBE84F"

[colors.normal]
black = "#000000"
blue = "#3464A3"
cyan = "#05979A"
green = "#4D9A05"
magenta = "#754F7B"
red = "#CC0000"
white = "#D3D6CF"
yellow = "#C3A000"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.search.focused_match]
background = "#C3A000"
foreground = "#CC0000"

[colors.search.matches]
background = "#C3A000"
foreground = "#3464A3"

[cursor]
blink_interval = 600
blink_timeout = 0
thickness = 0.15
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11

[font.bold]
family = "BitstromWera Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BitstromWera Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "BitstromWera Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "BitstromWera Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "None"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 20000

[selection]
save_to_clipboard = true

[window]
decorations_theme_variant = "Dark"
